-- 02_unload.sql: unload the raw tables and every dbt model to Parquet on the
-- internal stage MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT. Run after dbt build.
-- tools/sf.py unload runs this file and then GETs raw/ and expected/ into
-- exports/acme-snowflake-export/{raw,expected}/.
--
-- One file per table (SINGLE = TRUE), named <table>.parquet; column names are
-- kept (HEADER = TRUE) and stay upper-case. VARIANT columns are unloaded as
-- JSON text with TO_JSON(...) so they arrive in Molinia as plain strings; all
-- other columns keep their types. dbt models never contain VARIANT columns.

USE ROLE SYSADMIN;
USE WAREHOUSE DEMO_WH;
USE DATABASE MOLINIA_DEMO;

-------------------------------------------------------------------------------
-- Raw tables -> raw/<table>.parquet
-------------------------------------------------------------------------------

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/raw/customers.parquet
FROM (
    SELECT
        CUSTOMER_ID,
        FIRST_NAME,
        LAST_NAME,
        EMAIL,
        COUNTRY_CODE,
        SIGNUP_TS,
        MARKETING_OPT_IN
    FROM MOLINIA_DEMO.RAW.CUSTOMERS
)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/raw/customer_contacts.parquet
FROM (
    SELECT
        CUSTOMER_ID,
        PHONE,
        IBAN,
        DATE_OF_BIRTH
    FROM MOLINIA_DEMO.RAW.CUSTOMER_CONTACTS
)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/raw/products.parquet
FROM (
    SELECT
        PRODUCT_ID,
        SKU,
        PRODUCT_NAME,
        CATEGORY_CODE,
        UNIT_PRICE,
        IS_ACTIVE
    FROM MOLINIA_DEMO.RAW.PRODUCTS
)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/raw/orders.parquet
FROM (
    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        ORDER_TS,
        STATUS,
        CHANNEL,
        TO_JSON(ORDER_META) AS ORDER_META
    FROM MOLINIA_DEMO.RAW.ORDERS
)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/raw/order_items.parquet
FROM (
    SELECT
        ORDER_ITEM_ID,
        ORDER_ID,
        PRODUCT_ID,
        QUANTITY,
        UNIT_PRICE,
        DISCOUNT_PCT
    FROM MOLINIA_DEMO.RAW.ORDER_ITEMS
)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/raw/payments.parquet
FROM (
    SELECT
        PAYMENT_ID,
        ORDER_ID,
        PAYMENT_METHOD,
        AMOUNT_CENTS,
        STATUS,
        PAID_TS
    FROM MOLINIA_DEMO.RAW.PAYMENTS
)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/raw/web_events.parquet
FROM (
    SELECT
        EVENT_ID,
        CUSTOMER_ID,
        EVENT_TS,
        EVENT_TYPE,
        TO_JSON(PAYLOAD) AS PAYLOAD
    FROM MOLINIA_DEMO.RAW.WEB_EVENTS
)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

-------------------------------------------------------------------------------
-- dbt models (the answer key) -> expected/<model>.parquet
-------------------------------------------------------------------------------

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/stg_customers.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_STAGING.STG_CUSTOMERS)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/stg_products.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_STAGING.STG_PRODUCTS)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/stg_orders.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_STAGING.STG_ORDERS)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/stg_order_items.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_STAGING.STG_ORDER_ITEMS)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/stg_payments.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_STAGING.STG_PAYMENTS)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/int_order_lines.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_INTERMEDIATE.INT_ORDER_LINES)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/int_web_item_views.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_INTERMEDIATE.INT_WEB_ITEM_VIEWS)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/dim_customers.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_MARTS.DIM_CUSTOMERS)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/fct_orders.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_MARTS.FCT_ORDERS)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;

COPY INTO @MOLINIA_DEMO.PUBLIC.MOLINIA_EXPORT/expected/rpt_monthly_revenue.parquet
FROM (SELECT * FROM MOLINIA_DEMO.ANALYTICS_MARTS.RPT_MONTHLY_REVENUE)
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE
MAX_FILE_SIZE = 268435456;
